Fix remote-exec example
when used as it is it causes exception in validation
Error: Invalid reference
│   on main.tf line 33, in resource "vra7_deployment" "this":
│   33:     type     = ssh
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
Signed-off-by: Reddysekhar Gaduputi <gsekhar73@gmail.com>